import { SCENARIO_FORMAT, type ScenarioFile } from "./exercise.ts";

// Example scenario "Crue de l’Arve" (fictitious), shipped with the
// application: the injects of the demonstration exercise. The first five
// happened during the first two hours and a half of the demonstration; the
// others arrive while the visitor watches (src/exercise/demo.ts shifts them
// to "now"). Every name, number and place detail is fictitious.

/** Injects before this offset are the past of the demonstration. */
export const ARVE_PAST = 150;

export const ARVE_SCENARIO: ScenarioFile = {
  format: SCENARIO_FORMAT,
  version: 1,
  title: "Crue de l’Arve",
  description:
    "Exercice de conduite fictif : crue de l’Arve à Carouge (GE). Montée des eaux, fermeture des berges, sacs de sable, évacuation d’un quartier, hébergement et information de la population. Durée prévue : 4 heures.",
  injects: [
    {
      title: "Niveau de l’Arve en hausse",
      timing: "offset",
      offset: 8,
      clock: "",
      day: 0,
      from: "Patrouille Alpha",
      to: "PC arrière",
      via: "Radio",
      priority: "Important",
      category: "Renseignement",
      body: "Niveau en hausse rapide au pont des Acacias, environ 20 cm en 30 minutes.",
      delivery: "message",
      expected:
        "Consigner au journal, demander une reconnaissance, informer le chef d’intervention.",
      deadline: 10,
      effects: [],
    },
    {
      title: "Appel d’un riverain inquiet",
      timing: "offset",
      offset: 30,
      clock: "",
      day: 0,
      from: "Riverain (joué par la direction)",
      to: "Téléphoniste",
      via: "Téléphone",
      priority: "Normal",
      category: "Information",
      body: "« L’eau monte dans mon jardin au chemin de la Fontenette, est-ce qu’on doit partir ? » Répondre calmement, noter l’adresse.",
      delivery: "read",
      expected:
        "Noter l’adresse, consigner au journal, transmettre à la cellule situation.",
      deadline: 15,
      effects: [],
    },
    {
      title: "Eau sur la chaussée",
      timing: "offset",
      offset: 62,
      clock: "",
      day: 0,
      from: "Équipe Bravo",
      to: "PC front",
      via: "Radio",
      priority: "Urgent",
      category: "Alerte",
      body: "Eau sur la chaussée route de Veyrier à la hauteur de la Fontenette. Circulation dangereuse.",
      delivery: "message",
      expected:
        "Demander la fermeture de la route à la police, placer l’obstacle sur la carte.",
      deadline: 15,
      effects: [],
    },
    {
      title: "Sacs de sable en route",
      timing: "offset",
      offset: 70,
      clock: "",
      day: 0,
      from: "Logistique",
      to: "PC arrière",
      via: "Téléphone",
      priority: "Normal",
      category: "Compte rendu",
      body: "Deux camions partis de l’arsenal avec 200 sacs. Arrivée estimée dans 45 minutes.",
      delivery: "message",
      expected: "Mettre à jour l’état des moyens.",
      deadline: 0,
      effects: [],
    },
    {
      title: "Fermeture du pont",
      timing: "offset",
      offset: 74,
      clock: "",
      day: 0,
      from: "Police",
      to: "Chef d’intervention",
      via: "Téléphone",
      priority: "Normal",
      category: "Information",
      body: "La police ferme le pont de Carouge à la circulation dès 09:30.",
      delivery: "message",
      expected: "Informer les sections engagées de la déviation.",
      deadline: 0,
      effects: [],
    },
    {
      title: "Seuil d’alerte 2 atteint",
      timing: "offset",
      offset: 156,
      clock: "",
      day: 0,
      from: "Centrale d’engagement",
      to: "Cellule situation",
      via: "Message",
      priority: "Important",
      category: "Renseignement",
      body: "La station hydrométrique (fictive) des Acacias indique + 60 cm depuis le début de l’événement, montée de 12 cm par heure. Seuil d’alerte 2 atteint.",
      delivery: "message",
      expected:
        "Mettre à jour le renseignement clé, consigner, informer le chef d’intervention.",
      deadline: 10,
      effects: [
        {
          kind: "fact",
          label: "Niveau de l’Arve (Acacias)",
          value: "+ 60",
          unit: "cm",
        },
      ],
    },
    {
      title: "Camions arrivés au point de rassemblement",
      timing: "offset",
      offset: 159,
      clock: "",
      day: 0,
      from: "Logistique",
      to: "PC arrière",
      via: "Radio",
      priority: "Normal",
      category: "Compte rendu",
      body: "Les deux camions sont au point de rassemblement Acacias. Déchargement des sacs en cours.",
      delivery: "message",
      expected: "Mettre à jour l’état des moyens, quittancer.",
      deadline: 0,
      effects: [
        {
          kind: "resource",
          name: "Camions de transport PCi",
          status: "Engagé",
          location: "Point de rassemblement Acacias",
        },
        {
          kind: "resource",
          name: "Sacs de sable",
          status: "Engagé",
          location: "Point de rassemblement Acacias",
        },
      ],
    },
    {
      title: "Fortes pluies annoncées",
      timing: "offset",
      offset: 163,
      clock: "",
      day: 0,
      from: "Centrale d’engagement",
      to: "Cellule situation",
      via: "Message",
      priority: "Important",
      category: "Alerte",
      body: "Pluie forte sur le bassin de l’Arve pour les trois prochaines heures, 10 à 15 mm par heure, rafales à 50 km/h.",
      delivery: "message",
      expected: "Consigner, mettre à jour la météo, apprécier l’évolution.",
      deadline: 15,
      effects: [
        {
          kind: "observation",
          place: "Carouge (GE)",
          conditions: "Pluie forte, rafales",
          temperature: "11 °C",
          wind: "SO 35 km/h, rafales 50 km/h",
          precipitation: "12 mm/h",
        },
      ],
    },
    {
      title: "Personne bloquée dans un véhicule",
      timing: "offset",
      offset: 167,
      clock: "",
      day: 0,
      from: "Police",
      to: "Chef d’intervention",
      via: "Téléphone",
      priority: "Urgent",
      category: "Alerte",
      body: "Une conductrice est bloquée dans sa voiture, eau à mi-portière, route de Veyrier 120. Les pompiers sont demandés.",
      delivery: "message",
      expected:
        "Transmettre immédiatement au SIS, engager la réserve pour sécuriser, consigner la mission.",
      deadline: 5,
      effects: [],
    },
    {
      title: "Réserve en route",
      timing: "offset",
      offset: 171,
      clock: "",
      day: 0,
      from: "Section appui",
      to: "PC front",
      via: "Radio",
      priority: "Normal",
      category: "Compte rendu",
      body: "La section appui (réserve) quitte le PC Carouge, 12 personnes, arrivée dans 15 minutes.",
      delivery: "message",
      expected: "Mettre à jour l’état des moyens.",
      deadline: 0,
      effects: [
        {
          kind: "resource",
          name: "Section appui (réserve)",
          status: "En route",
          location: "PC Carouge → Route de Veyrier",
        },
      ],
    },
    {
      title: "Demande d’hébergement",
      timing: "offset",
      offset: 176,
      clock: "",
      day: 0,
      from: "Commune",
      to: "Chef AIC",
      via: "Téléphone",
      priority: "Important",
      category: "Demande",
      body: "La commune demande 30 places d’hébergement pour la nuit pour les habitants évacués du quartier de la Fontenette.",
      delivery: "message",
      expected:
        "Consigner la demande, créer la mission hébergement, désigner un responsable et une échéance.",
      deadline: 20,
      effects: [],
    },
    {
      title: "Caves inondées",
      timing: "offset",
      offset: 181,
      clock: "",
      day: 0,
      from: "Riverain",
      to: "Téléphoniste",
      via: "Téléphone",
      priority: "Normal",
      category: "Renseignement",
      body: "Trois caves inondées rue Jacques-Dalphin, pas de blessé, demande de motopompe.",
      delivery: "message",
      expected: "Consigner, décider de l’engagement d’une motopompe.",
      deadline: 30,
      effects: [],
    },
    {
      title: "Personnes évacuées",
      timing: "offset",
      offset: 187,
      clock: "",
      day: 0,
      from: "PC front",
      to: "Cellule situation",
      via: "Radio",
      priority: "Normal",
      category: "Compte rendu",
      body: "Six autres personnes évacuées du quartier de la Fontenette (18 en tout), regroupées à l’école des Pervenches.",
      delivery: "message",
      expected: "Mettre à jour le renseignement clé « Personnes évacuées ».",
      deadline: 10,
      effects: [
        {
          kind: "fact",
          label: "Personnes évacuées",
          value: "18",
          unit: "pers.",
        },
      ],
    },
    {
      title: "Point presse demandé",
      timing: "offset",
      offset: 193,
      clock: "",
      day: 0,
      from: "Journaliste (joué par la direction)",
      to: "Chef d’intervention",
      via: "Téléphone",
      priority: "Normal",
      category: "Demande",
      body: "Un journaliste de la presse locale (fictive) demande une déclaration sur l’évacuation. Répondre selon la ligne de communication.",
      delivery: "read",
      expected:
        "Renvoyer vers la cellule communication, consigner la demande, fixer un point presse à l’agenda.",
      deadline: 30,
      effects: [],
    },
    {
      title: "Niveau stabilisé",
      timing: "offset",
      offset: 200,
      clock: "",
      day: 0,
      from: "Patrouille Alpha",
      to: "PC arrière",
      via: "Radio",
      priority: "Normal",
      category: "Renseignement",
      body: "Niveau stable depuis 20 minutes au pont des Acacias, + 65 cm.",
      delivery: "message",
      expected: "Consigner, mettre à jour le renseignement clé.",
      deadline: 15,
      effects: [
        {
          kind: "fact",
          label: "Niveau de l’Arve (Acacias)",
          value: "+ 65",
          unit: "cm",
        },
      ],
    },
    {
      title: "Pluie faiblissante",
      timing: "offset",
      offset: 208,
      clock: "",
      day: 0,
      from: "Centrale d’engagement",
      to: "Cellule situation",
      via: "Message",
      priority: "Normal",
      category: "Information",
      body: "Les précipitations faiblissent, 2 mm par heure. Fin de l’alerte de fortes pluies attendue à 16 h.",
      delivery: "message",
      expected: "Mettre à jour la météo.",
      deadline: 0,
      effects: [
        {
          kind: "observation",
          place: "Carouge (GE)",
          conditions: "Pluie faible",
          temperature: "12 °C",
          wind: "SO 15 km/h",
          precipitation: "2 mm/h",
        },
      ],
    },
    {
      title: "Équipe Bravo de retour",
      timing: "offset",
      offset: 216,
      clock: "",
      day: 0,
      from: "Équipe Bravo",
      to: "PC front",
      via: "Radio",
      priority: "Normal",
      category: "Compte rendu",
      body: "Accès aux berges sécurisés, relevés par la section appui. Équipe Bravo de retour au PC pour la relève.",
      delivery: "message",
      expected: "Mettre à jour l’état des moyens, organiser la relève.",
      deadline: 0,
      effects: [
        {
          kind: "resource",
          name: "Équipe Bravo",
          status: "De retour",
          location: "PC Carouge",
        },
      ],
    },
  ],
};
