// Simple markers drawn from an icon (lucide or a few drawn here), each with a
// default colour and layer. Plain data so that the geographic exports can
// name them without React; symbols.tsx maps `icon` to the component.
// Names are shown in the language of the post (getter); `fr`, `group`,
// `layer` and the ids stay French: they are codes, compared and stored.

import { t, symbolLabel, symbolNames, type SymbolKey } from "./i18n-2.ts";

export type BuiltinInfo = {
  id: string;
  /** French name (stable, searched in every language). */
  fr: string;
  /** Name in the language of the post. */
  readonly name: string;
  /** Icon name (lucide-react export or one of the icons of symbols.tsx). */
  icon: string;
  color: string;
  /** Default layer, French (see standardLayer in maps.ts). */
  layer: string;
  /** Family, French (shown with groupLabel). */
  group: string;
  /** Synonyms for the search: French words and the names in DE / IT. */
  readonly keywords?: string;
};

export const BUILTIN_GROUPS = [
  "Conduite",
  "Personnes et accueil",
  "Sanitaire",
  "Secours et sécurité",
  "Dangers et effets",
  "Circulation",
  "Transports",
  "Logistique et réseaux",
  "Bâtiments",
  "Observation et information",
] as const;

const RED = "#e5243b";
const ORANGE = "#f08a00";
const AMBER = "#d99a00";
const GREEN = "#16a34a";
const BLUE = "#2563eb";
const CYAN = "#0891b2";
const VIOLET = "#7b5cff";
const PINK = "#db2777";
const SLATE = "#475569";
const BROWN = "#92400e";

const b = (
  id: string,
  name: SymbolKey,
  icon: string,
  color: string,
  layer: string,
  group: (typeof BUILTIN_GROUPS)[number],
  keywords = "",
): BuiltinInfo => ({
  id: `b:${id}`,
  fr: name,
  get name() {
    return symbolLabel(name);
  },
  icon,
  color,
  layer,
  group,
  get keywords() {
    return `${symbolNames(name)} ${keywords}`;
  },
});

export const BUILTIN_LIST: BuiltinInfo[] = [
  // Conduite
  b(
    "pc",
    "Poste de commandement",
    "Flag",
    VIOLET,
    "Emplacements",
    "Conduite",
    "pc poste conduite commandement etat-major",
  ),
  b(
    "pc-front",
    "PC front",
    "FlagTriangleRight",
    VIOLET,
    "Emplacements",
    "Conduite",
    "poste commandement avant engagement",
  ),
  b(
    "pc-arriere",
    "PC arrière",
    "Landmark",
    VIOLET,
    "Emplacements",
    "Conduite",
    "poste commandement arriere etat-major organe conduite",
  ),
  b(
    "centrale",
    "Centrale d’engagement",
    "Headset",
    VIOLET,
    "Emplacements",
    "Conduite",
    "centrale alarme engagement 118 144 117 cet",
  ),
  b(
    "liaison",
    "Officier de liaison",
    "Handshake",
    VIOLET,
    "Emplacements",
    "Conduite",
    "liaison partenaire coordination",
  ),
  b(
    "rencontre",
    "Point de rencontre",
    "MapPin",
    VIOLET,
    "Emplacements",
    "Conduite",
    "rendez-vous rdv point de rencontre accueil des moyens",
  ),
  b(
    "checkpoint",
    "Check-point",
    "ShieldCheck",
    SLATE,
    "Mesures",
    "Conduite",
    "controle poste de controle acces filtrage",
  ),
  b(
    "relais",
    "Relais radio · antenne",
    "RadioTower",
    SLATE,
    "Moyens",
    "Conduite",
    "radio relais antenne polycom telematique transmission",
  ),
  b(
    "radio",
    "Poste radio",
    "Radio",
    SLATE,
    "Moyens",
    "Conduite",
    "radio polycom telematique",
  ),

  // Personnes et accueil
  b(
    "rassemblement",
    "Point de rassemblement",
    "Users",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "rassemblement regroupement evacues",
  ),
  b(
    "sinistres",
    "Place sinistrés",
    "UsersRound",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "sinistres victimes personnes touchees",
  ),
  b(
    "collecteur-sinistres",
    "Poste collecteur de sinistrés",
    "Footprints",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "poste collecteur sinistres personnes",
  ),
  b(
    "accueil",
    "Centre d’accueil",
    "HandHeart",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "accueil centre prise en charge",
  ),
  b(
    "hebergement",
    "Hébergement",
    "BedDouble",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "hebergement dortoir abri nuit logement",
  ),
  b(
    "subsistance",
    "Subsistance · ravitaillement",
    "UtensilsCrossed",
    GREEN,
    "Mesures",
    "Personnes et accueil",
    "subsistance ravitaillement repas cuisine nourriture",
  ),
  b(
    "boissons",
    "Eau potable · boissons",
    "GlassWater",
    CYAN,
    "Mesures",
    "Personnes et accueil",
    "eau potable boisson distribution",
  ),
  b(
    "toilettes",
    "Toilettes",
    "Toilet",
    SLATE,
    "Mesures",
    "Personnes et accueil",
    "wc toilettes sanitaires",
  ),
  b(
    "douches",
    "Douches",
    "ShowerHead",
    SLATE,
    "Mesures",
    "Personnes et accueil",
    "douche hygiene",
  ),
  b(
    "evacuation",
    "Évacuation",
    "DoorOpen",
    ORANGE,
    "Mesures",
    "Personnes et accueil",
    "evacuation sortie fuite",
  ),
  b(
    "disparu",
    "Personne disparue",
    "UserSearch",
    RED,
    "Effets",
    "Personnes et accueil",
    "disparu disparue recherche personne",
  ),
  b(
    "recherche",
    "Recherche",
    "Search",
    ORANGE,
    "Mesures",
    "Personnes et accueil",
    "recherche fouille sauvetage",
  ),
  b(
    "enfants",
    "Enfants",
    "Baby",
    PINK,
    "Effets",
    "Personnes et accueil",
    "enfants creche",
  ),
  b(
    "vulnerables",
    "Personnes vulnérables",
    "Accessibility",
    PINK,
    "Effets",
    "Personnes et accueil",
    "handicap mobilite reduite vulnerables ems",
  ),

  // Sanitaire
  b(
    "sanitaire",
    "Blessés · sanitaire",
    "Cross",
    RED,
    "Effets",
    "Sanitaire",
    "blesses sanitaire croix",
  ),
  b(
    "collecteur-blesses",
    "Poste collecteur de blessés",
    "HeartPulse",
    RED,
    "Mesures",
    "Sanitaire",
    "poste collecteur blesses triage nid de blesses",
  ),
  b(
    "poste-sanitaire",
    "Poste sanitaire",
    "BriefcaseMedical",
    RED,
    "Mesures",
    "Sanitaire",
    "poste sanitaire pma poste medical avance soins",
  ),
  b(
    "ambulance",
    "Ambulance",
    "Ambulance",
    RED,
    "Moyens",
    "Sanitaire",
    "ambulance 144 smur",
  ),
  b(
    "hopital",
    "Hôpital",
    "Hospital",
    RED,
    "Emplacements",
    "Sanitaire",
    "hopital clinique urgences",
  ),
  b(
    "medecin",
    "Médecin",
    "Stethoscope",
    RED,
    "Moyens",
    "Sanitaire",
    "medecin docteur",
  ),
  b(
    "pharmacie",
    "Pharmacie · médicaments",
    "Pill",
    RED,
    "Emplacements",
    "Sanitaire",
    "pharmacie medicaments",
  ),
  b(
    "psy",
    "Soutien psychologique",
    "HeartHandshake",
    PINK,
    "Mesures",
    "Sanitaire",
    "care team soutien psychologique",
  ),
  b(
    "decontamination",
    "Décontamination",
    "ShowerHead",
    CYAN,
    "Mesures",
    "Sanitaire",
    "decontamination deco nbc lavage",
  ),
  b(
    "morgue",
    "Dépôt mortuaire",
    "Skull",
    SLATE,
    "Mesures",
    "Sanitaire",
    "depot mortuaire morgue deces",
  ),

  // Secours et sécurité
  b(
    "pompiers",
    "Pompiers",
    "FireExtinguisher",
    RED,
    "Moyens",
    "Secours et sécurité",
    "pompiers sis feu 118",
  ),
  b(
    "police",
    "Police",
    "Shield",
    BLUE,
    "Moyens",
    "Secours et sécurité",
    "police gendarmerie 117",
  ),
  b(
    "armee",
    "Armée",
    "ShieldHalf",
    "#4d7c0f",
    "Moyens",
    "Secours et sécurité",
    "armee militaire troupe",
  ),
  b(
    "pci",
    "Protection civile",
    "CivilProtection",
    ORANGE,
    "Moyens",
    "Secours et sécurité",
    "protection civile pci pbc",
  ),
  b(
    "sauvetage",
    "Sauvetage",
    "LifeBuoy",
    ORANGE,
    "Moyens",
    "Secours et sécurité",
    "sauvetage secours bouee",
  ),
  b(
    "chien",
    "Chien de recherche",
    "Dog",
    BROWN,
    "Moyens",
    "Secours et sécurité",
    "chien cynologue recherche",
  ),
  b(
    "sirene",
    "Alarme · sirène",
    "Siren",
    RED,
    "Mesures",
    "Secours et sécurité",
    "sirene alarme alerte population",
  ),
  b(
    "vehicule",
    "Véhicule",
    "Truck",
    BLUE,
    "Moyens",
    "Secours et sécurité",
    "vehicule camion engin",
  ),

  // Dangers et effets
  b(
    "incident",
    "Incident",
    "Flame",
    "#f0443a",
    "Effets",
    "Dangers et effets",
    "incident evenement sinistre",
  ),
  b(
    "danger",
    "Danger",
    "TriangleAlert",
    "#f59e0b",
    "Dangers",
    "Dangers et effets",
    "danger attention",
  ),
  b(
    "incendie",
    "Incendie",
    "Flame",
    RED,
    "Effets",
    "Dangers et effets",
    "incendie feu flammes",
  ),
  b(
    "fumee",
    "Fumée",
    "CloudFog",
    SLATE,
    "Effets",
    "Dangers et effets",
    "fumee nuage brouillard",
  ),
  b(
    "explosif",
    "Explosion · explosif",
    "Bomb",
    RED,
    "Dangers",
    "Dangers et effets",
    "explosion explosif bombe",
  ),
  b(
    "chimique",
    "Chimique",
    "FlaskConical",
    ORANGE,
    "Dangers",
    "Dangers et effets",
    "chimique chimie produit toxique nbc",
  ),
  b(
    "radiologique",
    "Radiologique",
    "Radiation",
    AMBER,
    "Dangers",
    "Dangers et effets",
    "radiologique nucleaire radioactif nbc",
  ),
  b(
    "biologique",
    "Biologique",
    "Biohazard",
    ORANGE,
    "Dangers",
    "Dangers et effets",
    "biologique epidemie virus nbc",
  ),
  b(
    "inondation",
    "Inondation",
    "Waves",
    CYAN,
    "Effets",
    "Dangers et effets",
    "inondation crue eau hochwasser",
  ),
  b(
    "glissement",
    "Glissement de terrain",
    "Mountain",
    BROWN,
    "Effets",
    "Dangers et effets",
    "glissement terrain eboulement lave torrentielle",
  ),
  b(
    "avalanche",
    "Avalanche",
    "MountainSnow",
    CYAN,
    "Effets",
    "Dangers et effets",
    "avalanche neige",
  ),
  b(
    "tempete",
    "Tempête",
    "Wind",
    SLATE,
    "Effets",
    "Dangers et effets",
    "tempete vent ouragan",
  ),
  b(
    "orage",
    "Orage",
    "CloudLightning",
    VIOLET,
    "Effets",
    "Dangers et effets",
    "orage foudre grele",
  ),
  b(
    "effondrement",
    "Effondrement",
    "BrickWall",
    BROWN,
    "Effets",
    "Dangers et effets",
    "effondrement batiment ruine decombres",
  ),
  b(
    "electricite-danger",
    "Danger électrique",
    "Zap",
    AMBER,
    "Dangers",
    "Dangers et effets",
    "electrique ligne haute tension courant",
  ),
  b(
    "gaz-fuite",
    "Fuite de gaz",
    "Cylinder",
    ORANGE,
    "Dangers",
    "Dangers et effets",
    "gaz fuite",
  ),
  b(
    "pollution",
    "Pollution",
    "Droplet",
    "#4b5563",
    "Effets",
    "Dangers et effets",
    "pollution hydrocarbures huile",
  ),
  b(
    "animaux",
    "Animaux",
    "PawPrint",
    BROWN,
    "Effets",
    "Dangers et effets",
    "animaux betail epizootie",
  ),
  b(
    "verglas",
    "Neige · verglas",
    "Snowflake",
    CYAN,
    "Effets",
    "Dangers et effets",
    "neige verglas gel",
  ),

  // Circulation
  b(
    "barrage",
    "Barrage",
    "Ban",
    "#dc2626",
    "Mesures",
    "Circulation",
    "barrage bouclage fermeture",
  ),
  b(
    "route-coupee",
    "Route coupée",
    "RouteOff",
    RED,
    "Effets",
    "Circulation",
    "route coupee fermee impraticable",
  ),
  b(
    "deviation",
    "Déviation",
    "Split",
    ORANGE,
    "Mesures",
    "Circulation",
    "deviation itineraire detour",
  ),
  b(
    "zone-interdite",
    "Zone interdite",
    "OctagonX",
    RED,
    "Mesures",
    "Circulation",
    "zone interdite acces interdit perimetre",
  ),
  b(
    "chantier",
    "Chantier · travaux",
    "Construction",
    ORANGE,
    "Mesures",
    "Circulation",
    "chantier travaux",
  ),
  b(
    "balisage",
    "Balisage",
    "TrafficCone",
    ORANGE,
    "Mesures",
    "Circulation",
    "balisage cone signalisation",
  ),
  b(
    "parking",
    "Parking",
    "SquareParking",
    BLUE,
    "Mesures",
    "Circulation",
    "parking stationnement place",
  ),
  b(
    "pont",
    "Pont",
    "Bridge",
    SLATE,
    "Emplacements",
    "Circulation",
    "pont passerelle viaduc",
  ),
  b(
    "signalisation",
    "Signalisation",
    "Signpost",
    SLATE,
    "Mesures",
    "Circulation",
    "panneau signalisation direction",
  ),

  // Transports
  b("voiture", "Voiture", "Car", BLUE, "Moyens", "Transports", "voiture auto"),
  b(
    "bus",
    "Bus · car",
    "Bus",
    BLUE,
    "Moyens",
    "Transports",
    "bus car transport",
  ),
  b(
    "helicoptere",
    "Hélicoptère",
    "Helicopter",
    BLUE,
    "Moyens",
    "Transports",
    "helicoptere rega",
  ),
  b(
    "heliport",
    "Héliport · place d’atterrissage",
    "Heliport",
    BLUE,
    "Emplacements",
    "Transports",
    "heliport helistation place atterrissage h",
  ),
  b("avion", "Avion", "Plane", BLUE, "Moyens", "Transports", "avion aeronef"),
  b("drone", "Drone", "Drone", VIOLET, "Moyens", "Transports", "drone uav"),
  b(
    "bateau",
    "Bateau",
    "Ship",
    CYAN,
    "Moyens",
    "Transports",
    "bateau navire embarcation",
  ),
  b(
    "train",
    "Train",
    "TrainFront",
    SLATE,
    "Moyens",
    "Transports",
    "train rail chemin de fer cff",
  ),
  b(
    "engin",
    "Engin de chantier",
    "Tractor",
    AMBER,
    "Moyens",
    "Transports",
    "engin chantier tracteur trax",
  ),

  // Logistique et réseaux
  b(
    "depot",
    "Dépôt de matériel",
    "Warehouse",
    BROWN,
    "Emplacements",
    "Logistique et réseaux",
    "depot entrepot materiel stock",
  ),
  b(
    "materiel",
    "Matériel",
    "Package",
    BROWN,
    "Moyens",
    "Logistique et réseaux",
    "materiel colis caisse",
  ),
  b(
    "carburant",
    "Carburant",
    "Fuel",
    AMBER,
    "Emplacements",
    "Logistique et réseaux",
    "carburant essence diesel station",
  ),
  b(
    "generateur",
    "Générateur",
    "PlugZap",
    AMBER,
    "Moyens",
    "Logistique et réseaux",
    "generateur groupe electrogene courant",
  ),
  b(
    "electricite",
    "Électricité",
    "Zap",
    AMBER,
    "Emplacements",
    "Logistique et réseaux",
    "electricite courant transformateur",
  ),
  b(
    "gaz",
    "Gaz",
    "Cylinder",
    ORANGE,
    "Emplacements",
    "Logistique et réseaux",
    "gaz vanne conduite",
  ),
  b(
    "eau",
    "Point d’eau · hydrante",
    "Droplets",
    CYAN,
    "Moyens",
    "Logistique et réseaux",
    "eau hydrante borne incendie point eau",
  ),
  b(
    "tente",
    "Tente",
    "Tent",
    GREEN,
    "Mesures",
    "Logistique et réseaux",
    "tente abri camp",
  ),
  b(
    "atelier",
    "Atelier · réparation",
    "Wrench",
    SLATE,
    "Emplacements",
    "Logistique et réseaux",
    "atelier reparation maintenance",
  ),
  b(
    "dechets",
    "Déchets",
    "Trash2",
    SLATE,
    "Mesures",
    "Logistique et réseaux",
    "dechets poubelle ordures",
  ),
  b(
    "telecom",
    "Télécommunications",
    "Antenna",
    SLATE,
    "Emplacements",
    "Logistique et réseaux",
    "telecom antenne reseau telephone",
  ),

  // Bâtiments
  b(
    "batiment",
    "Bâtiment",
    "Building2",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "batiment immeuble",
  ),
  b(
    "maison",
    "Maison",
    "House",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "maison habitation",
  ),
  b(
    "ecole",
    "École",
    "School",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "ecole college",
  ),
  b(
    "eglise",
    "Église",
    "Church",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "eglise temple chapelle",
  ),
  b(
    "usine",
    "Usine · industrie",
    "Factory",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "usine industrie entreprise",
  ),
  b("hotel", "Hôtel", "Hotel", SLATE, "Emplacements", "Bâtiments", "hotel"),
  b(
    "commerce",
    "Commerce",
    "Store",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "magasin commerce",
  ),
  b(
    "public",
    "Bâtiment public",
    "Landmark",
    SLATE,
    "Emplacements",
    "Bâtiments",
    "mairie commune administration",
  ),

  // Observation et information
  b(
    "observation",
    "Point de vue · observation",
    "Binoculars",
    VIOLET,
    "Mesures",
    "Observation et information",
    "observation point de vue guet surveillance",
  ),
  b(
    "camera",
    "Caméra · photo",
    "Camera",
    SLATE,
    "Mesures",
    "Observation et information",
    "camera photo",
  ),
  b(
    "video",
    "Vidéosurveillance",
    "Cctv",
    SLATE,
    "Mesures",
    "Observation et information",
    "video surveillance webcam",
  ),
  b(
    "medias",
    "Médias · presse",
    "Newspaper",
    PINK,
    "Emplacements",
    "Observation et information",
    "medias presse journalistes",
  ),
  b(
    "information-pop",
    "Information à la population",
    "Megaphone",
    PINK,
    "Mesures",
    "Observation et information",
    "information population haut-parleur",
  ),
  b(
    "info",
    "Information",
    "Info",
    "#0ea5e9",
    "Autre",
    "Observation et information",
    "information renseignement",
  ),
  b(
    "heure",
    "Heure · échéance",
    "Clock3",
    SLATE,
    "Autre",
    "Observation et information",
    "heure echeance rendez-vous",
  ),
  b(
    "cible",
    "Objectif",
    "Target",
    RED,
    "Autre",
    "Observation et information",
    "objectif cible",
  ),
  b(
    "point",
    "Point",
    "",
    "#8b7bff",
    "Autre",
    "Observation et information",
    "point repere marque",
  ),
];

const BY_ID = new Map(BUILTIN_LIST.map((x) => [x.id, x]));
export const builtinInfo = (id: string) => BY_ID.get(id);

/** Official symbols: 16 hex characters. Custom symbols: "c:<uuid>". */
export const OFFICIAL = /^[0-9a-f]{16}$/;
export const CUSTOM_PREFIX = "c:";
export const isCustom = (id: string) => id.startsWith(CUSTOM_PREFIX);
export const customId = (id: string) => id.slice(CUSTOM_PREFIX.length);

/** Names of the official symbols, filled once the catalog is loaded. */
export const officialNames = new Map<string, string>();

/** Family of a symbol (simple markers, official catalog) in the language of the post. */
export const groupLabel = (group: string) => symbolLabel(group);

/** Human name of a symbol value, whatever its kind. */
export function symbolName(
  id: string,
  customs: readonly { id: string; name: string }[] = [],
): string {
  if (!id) return "";
  const known = builtinInfo(id);
  if (known) return known.name;
  if (isCustom(id))
    return customs.find((c) => c.id === customId(id))?.name ?? t("Signe");
  if (OFFICIAL.test(id)) {
    const name = officialNames.get(id);
    return name ? symbolLabel(name) : t("Signe officiel");
  }
  return t("Signe");
}
